from __future__ import annotations

"""Central status constants for the conservative SCM ID layer."""

from typing import Dict

ID_ALGORITHM_VERSION = 47
ID_ALGORITHM_STATUS = "limited_scaffold_with_recursive_id_step29_authority_separation_formula_ast_step42_ast_runtime_step43_q_input_recursion_step44_q_factor_general_recursion_step45_carried_q_context_step51_carried_q_ast_step52_exact_fail_branch_hedge_step46_and_canonical_proof_trace_step47_completeness_matrix_step48_full_id_public_facade_step49_canonical_control_flow_step50_carried_q_context_step51_carried_q_ast_step52_operational_carried_q_ast_step53_ast_normalizer_step54_canonical_formula_authority_step55_canonical_id7_carried_q_formula_step56_idc_normalization_step57_full_id_readiness_matrix_step58_canonical_id4_formula_authority_step59_contextual_id7_step60_failure_certificates_step61_idc_pruning_step62_agentic_full_id_adapter_step63_symbolic_ast_evaluator_step64_idc_fraction_numeric_step65_chain_frontdoor_and_q_factor_numeric_step66_parallel_frontdoor_set_step67_failure_authority_separation_step68_do_proof_metadata_step73_canonical_templates_step74"

ID_CAPABILITY_FLAGS: Dict[str, object] = {
    "id_algorithm_version": ID_ALGORITHM_VERSION,
    "id_algorithm_status": ID_ALGORITHM_STATUS,
    "full_recursive_id_implemented": 0,
    "full_id_claim_allowed": 0,
    "diagnostic_authority_separation_step41_implemented": 1,
    "full_recursive_id_step2_implemented": 1,
    "full_recursive_id_step3_implemented": 1,
    "full_recursive_id_step4_implemented": 1,
    "general_q_input_recursion_step44_implemented": 1,
    "full_recursive_id_step5_partial_implemented": 1,
    "q_factor_general_recursion_step45_implemented": 1,
    "exact_fail_branch_hedge_step46_implemented": 1,
    "canonical_id_proof_trace_step47_implemented": 1,
    "id_completeness_matrix_step48_implemented": 1,
    "id_full_public_facade_step49_implemented": 1,
    "id_full_canonical_control_flow_step50_implemented": 1,
    "id_full_carried_q_context_step51_implemented": 1,
    "id_full_carried_q_ast_step52_implemented": 1,
    "id_full_operational_carried_q_ast_step53_implemented": 1,
    "id_full_formula_ast_normalizer_step54_implemented": 1,
    "id_full_canonical_formula_authority_step55_implemented": 1,
    "id_full_canonical_id7_carried_q_formula_step56_implemented": 1,
    "id_full_idc_normalization_step57_implemented": 1,
    "id_full_readiness_matrix_step58_implemented": 1,
    "id_full_canonical_id4_formula_authority_step59_implemented": 1,
    "id_full_contextual_id7_carried_q_formula_step60_implemented": 1,
    "id_full_failure_certificates_step61_implemented": 1,
    "id_full_idc_pruning_step62_implemented": 1,
    "id_full_agentic_adapter_step63_implemented": 1,
    "id_full_symbolic_ast_evaluator_step64_implemented": 1,
    "id_full_idc_fraction_numeric_step65_implemented": 1,
    "id_full_chain_frontdoor_id7_step66_implemented": 1,
    "id_full_q_factor_numeric_step66_implemented": 1,
    "id_full_parallel_frontdoor_set_id7_step67_implemented": 1,
    "id_full_failure_authority_separation_step68_implemented": 1,
    "id_full_do_proof_metadata_step73_implemented": 1,
    "id_full_do_canonical_proof_templates_step74_implemented": 1,
    "id_full_agentic_adapter_step63_level": "amantia_causal_core_identification_engine_routes_online_agentic_queries_to_full_id_and_idc_pruning_set_valued_treatments_outcomes_conditions_no_full_id_claim",
    "id_full_symbolic_ast_evaluator_step64_level": "symbolic_evaluator_accepts_normalized_formula_ast_json_and_routes_sum_product_fraction_do_q_factor_hedge_fail_nodes_conservatively_no_full_id_claim",
    "id_full_idc_fraction_numeric_step65_level": "resolved_IDC_fraction_ASTs_route_to_contract_gated_symbolic_numeric_idc_fraction_ratio_conditional_mean_standardization_Q_placeholder_hedge_nodes_remain_blocked_no_full_id_claim",
    "id_full_chain_frontdoor_id7_step66_level": "narrow_two_or_more_mediator_chain_frontdoor_ID7_carried_Q_formula_for_X_to_Z_chain_to_Y_with_X_bidirected_Y_no_arbitrary_ID7_claim",
    "id_full_q_factor_numeric_step66_level": "resolved_Q_factor_ASTs_with_probability_sum_product_do_children_route_to_contract_gated_standardization_bare_or_nested_Q_inputs_remain_blocked_no_full_id_claim",
    "id_full_parallel_frontdoor_set_id7_step67_level": "strict_multi_mediator_parallel_frontdoor_set_ID7_carried_Q_formula_for_X_to_each_Z_and_each_Z_to_Y_with_X_bidirected_Y_no_extra_edges_no_arbitrary_ID7_claim",
    "id_full_failure_authority_separation_step68_level": "nonidentified_full_id_outputs_use_id_failure_certificate_step68_as_primary_non_formula_authority_so_readiness_delegate_counts_only_identified_formula_construction_no_full_id_claim",
    "id_full_do_proof_metadata_step73_level": "full_id_attaches_bounded_do_calculus_proof_engine_result_as_audit_metadata_only_no_formula_authority_no_full_id_claim_no_veto_authority",
    "id_full_do_canonical_proof_templates_step74_level": "bounded_do_calculus_proof_engine_uses_audit_only_canonical_zero_effect_backdoor_and_limited_frontdoor_templates_no_formula_authority_no_full_id_claim_no_veto_authority",
    "id_full_public_facade_level": "set_valued_full_id_shaped_api_with_canonical_id_1_to_7_control_flow_owned_formula_authority_ID1_ID2_ID4_ID6_gated_ID7_frontdoor_contextual_IDC_ratio_normalization_and_IDC_pruning_no_full_id_claim",
    "id_full_failure_certificates_step61_level": "standardized_failure_certificate_channel_for_full_id_and_idc_nonidentified_outputs_formal_hedge_when_certified_else_explicit_technical_pending_no_full_id_claim",
    "id_full_idc_pruning_step62_level": "conservative_IDC_condition_pruning_removes_conditions_disconnected_from_outcomes_after_doX_before_ratio_over_identified_joint_no_full_idc_claim",
    "id_full_canonical_control_flow_level": "machine_readable_ID_1_to_ID_7_orchestrator_overlay_before_recursive_expression_delegate",
    "id_full_carried_q_context_level": "explicit_Q_scope_Q_terms_and_projection_metadata_for_ID_7_carried_q_recursion_no_full_id_claim",
    "id_full_carried_q_ast_level": "carried_Q_context_exposes_id_ast_v1_formula_ast_for_ID_7_Q_input_no_full_id_claim",
    "id_full_operational_carried_q_ast_level": "recursive_runtime_accepts_carried_Q_formula_ast_as_operational_Q_input_for_supported_ID_7_base_and_full_district_branches_no_full_id_claim",
    "id_full_formula_ast_normalizer_level": "recursive_ID_expression_payloads_serialize_normalized_id_ast_v1_nodes_for_sum_product_fraction_do_q_factor_and_hedge_fail_no_full_id_claim",
    "id_full_canonical_formula_authority_level": "owned_formula_authority_for_canonical_ID_1_ID_2_ID_4_and_ID_6_branches_no_full_id_claim",
    "id_full_canonical_id4_formula_authority_step59_level": "canonical_ID4_district_decomposition_product_with_recursive_canonical_subproblem_formulas_reduces_delegate_authority_no_full_id_claim",
    "id_full_canonical_id7_carried_q_formula_level": "gated_classic_and_contextual_frontdoor_shaped_ID7_carried_Q_formula_with_alpha_renamed_treatment_prime_and_direct_confounding_fail_guard_no_full_id_claim",
    "id_full_idc_normalization_step57_level": "conditional_interventional_distribution_api_identifies_P_Y_given_do_X_Z_as_ratio_over_identified_joint_P_YZ_given_do_X_no_new_full_id_claim",
    "id_full_readiness_matrix_step58_level": "18_case_public_full_id_and_idc_readiness_matrix_covering_canonical_ID6_ID7_frontdoor_Q_factor_hedge_invalid_cycle_multi_set_and_IDC_ratio_cases_no_full_id_claim",
    "id_full_contextual_id7_carried_q_formula_step60_level": "canonical_contextual_frontdoor_joint_outcome_formula_for_P_YC_given_do_X_enables_IDC_joint_authority_no_full_id_claim",
    "formal_hedge_authority_level": "certified_only_from_recursive_id_fail_branch_not_from_standalone_diagnostic",
    "q_factor_general_recursion_level": "standalone_q_factor_module_delegates_strict_subdistrict_q_input_queries_to_recursive_expression_runtime_with_step51_carried_q_context",
    "formal_hedge_certificate_step27_implemented": 1,
    "localized_hedge_certificate_step28_implemented": 1,
    "set_valued_q_input_recursion_step29_implemented": 1,
    "q_input_subdistrict_recursion_step23_implemented": 1,
    "set_valued_recursive_expression_api_step24_implemented": 1,
    "q_input_formula_alpha_renaming_step24_implemented": 1,
    "recursive_id_skeleton_implemented": 1,
    "hedge_detection_level": "ancestral_c_component_witness_diagnostic_strict_roots",
    "formal_hedge_construction_implemented": 1,
    "formal_hedge_candidate_diagnostic_implemented": 1,
    "d_separation_diagnostic_level": "latent_expanded_admg_paths",
    "frontdoor_diagnostic_level": "limited_pearl_conditions_with_dsep",
    "observed_dag_factorization_level": "explicit_truncated_factorization_formula",
    "c_component_diagnostic_level": "ancestral_district_decomposition_with_q_placeholders",
    "recursive_id_diagnostic_level": "ancestor_reduction_w_step_observed_dag_base_case_district_decomposition_q_factor_step2_q_input_subdistrict_step3_formal_hedge_candidate",
    "recursive_id_expression_level": "set_valued_recursive_expression_step29_multi_intervention_q_input_q_factor_step4_localized_formal_hedge_certificate_ast_runtime_step43_structured_q_input_recursion_step44_q_factor_general_recursion_step45_carried_q_context_step51_carried_q_ast_step52_operational_carried_q_ast_step53_exact_fail_branch_hedge_step46",
    "c_factor_decomposition_level": "ancestral_district_product_with_q_placeholders",
    "symbolic_formula_layer_implemented": 1,
    "formula_ast_step42_implemented": 1,
    "formula_ast_runtime_step43_implemented": 1,
    "formula_ast_runtime_level": "recursive_expression_builds_ast_internally_for_supported_branches_and_uses_carried_q_input_subproblem_ast_operationally_with_parser_fallback_then_normalizes_AST_shape_step54",
    "formula_ast_version": "id_ast_v1",
    "symbolic_formula_level": "structured_json_terms_with_id_ast_v1_for_supported_limited_estimands_carried_Q_contexts_and_unresolved_c_factors",
    "id_proof_trace_implemented": 1,
    "id_proof_trace_level": "machine_readable_route_steps_formula_tree_and_canonical_id_1_to_7_overlay_no_new_authority",
    "canonical_id_proof_trace_level": "maps_recursive_runtime_trace_to_ID_1_no_intervention_ID_2_ancestor_reduction_ID_3_w_step_ID_4_district_decomposition_ID_5_fail_hedge_ID_6_q_factor_ID_7_q_input_recursion",
    "id_completeness_matrix_level": "step48_regression_gate_observed_dag_backdoor_frontdoor_zero_effect_formal_hedge_and_district_q_factor_cases_no_full_id_claim",
    "id_full_readiness_matrix_version": "id_full_readiness_matrix_v8_step68",
    "id_authority_layer_level": "recursive_id_preferred_authority_with_backdoor_frontdoor_as_diagnostic_shortcuts",
    "recursive_subproblem_planner_implemented": 1,
    "recursive_subproblem_planner_level": "machine_readable_district_q_factor_subproblem_plan_no_new_authority",
}


def id_capability_flags() -> Dict[str, object]:
    return dict(ID_CAPABILITY_FLAGS)


__all__ = ["ID_ALGORITHM_STATUS", "ID_ALGORITHM_VERSION", "ID_CAPABILITY_FLAGS", "id_capability_flags"]
